### ISSUE TITLE
webserver source code

### ISSUE THREAD

**Issue by emanueledelsozzo** [cambridgehackers/zynq-boot#2]
The documentation doesn't link the new web server source code. Is it closed? I can't find nowhere.

**Comment by jameyhicks** [comment]
It is in a funny place. I developed it so that I could build a browser-based development environment, and so that code is in the webui repository:
    https://github.com/cambridgehackers/webui/blob/master/src/zedboard-server.c
- I will update the readme to point to it. 
- I should also update the Makefile to build it.

**Comment by jameyhicks** [comment]
Updated the readme and Makefile.
